### ISSUE TITLE
keytree: serialization for xpub, xprv

### ISSUE THREAD

**Issue by oleganza** [interstellar/slingshot#179]
For both `Xprv` and `Xpub` types:

* `::to_bytes(&self) -> [u8; 64]`
* `::from_bytes(&[u8]) -> Option<Self>` (checking that slice is exactly 64-byte-long)

For later: implement Serde on top of these ([example](https://github.com/dalek-cryptography/ed25519-dalek/blob/master/src/public.rs#L249-L285))

Note: the `from_bytes` won't benefit from using fixed-length array (`[u8; 64]`) because at least `Xprv` would still have to check if scalar is canonically encoded. So we might as well make decoding of all of these failable and take byteslices to let user not to make extra 64-byte copies.

**Comment by tessr** [comment]
What should be serialized/deserialized here? For the private key, is the deserialized form composed of the deserialized scalar (a u8 of length 32) followed by the deserialized derivation key (also a u8 of length 32)? For the pub key, is it the same thing but the deserialized point instead of the scalar?

**Comment by oleganza** [comment]
Yes:

`xprv = <scalar 32 bytes> <dk 32 bytes>`
`xpub = <point 32 bytes> <dk 32 bytes>`

Now that Xpub holds a decompressed point, the `Option<Xpub>` returned by decoding `&[u8]` can also fail because `decompress()` fails (not only on len()!=64).

**Comment by oleganza** [comment]
(clicked wrong button)

**Comment by tessr** [comment]
Resolved by https://github.com/interstellar/slingshot/pull/228
